### PR TITLE
feat: add help texts to fields

### PR DESCRIPTION
**Pull request by arnevandoorslaer**

### CODE REVIEW

**Comment by arnevandoorslaer** [comment]
image
image

**Comment by arnevandoorslaer** [comment]
image
image

**Comment by lem-onade** [comment]
@sdevalk @ddeboer What do you think? To me, the help texts seem a bit long (especially the date field).

Should "Bijvoorbeeld: ...." be used as placeholders of the input fields or should they be part of the description?

**Comment by sdevalk** [comment]
> @sdevalk @ddeboer What do you think? To me, the help texts seem a bit long (especially the date field).
> 
> Should "Bijvoorbeeld: ...." be used as placeholders of the input fields or should they be part of the description?

@lem-onade Thanks! Yes, the texts are a bit long. But the presentation is quite clear: the help texts are smaller and have a lighter color, so I don't think they disturb the user interface that much [*]. The 'Datum' field is an exception, though. Then again: that field needs a good description with examples; otherwise the EDTF options aren't explained properly. Perhaps we could move this to a separate help/support page (that could popup if a user clicks on some icon next to the input field). But this probably takes too much effort at this stage. So, in short: I think the current design suffices.

@ddeboer What do you think?

[*] Although some additional margin between the input field and the help text could help :)

**Pull request merged**
