### PR TITLE
fix: errors when creating new objects

### PR DESCRIPTION
**Pull request by lem-onade**

### CODE REVIEW

**Review by arnevandoorslaer — APPROVED** [review]

**Comment by pietervaneverdingen** [comment]
The content of my first Inrupt data space pod solidcrstest1 is not available anymore (around 20 images) and it gives the "Oeps er ging iets mis" error when I try to create a new object in a collection.

With another Solid app that was developed 1,5 years ago the procedure was when we had a new release of the app: 
1) Delete your current pod, 
2) Create a new pod with the same name (or another name) and 
3) Start using the new release from scratch and create some new content again to test the application

But also with a new empty Inrupt data space pod solidcrstest4 and when use the app as a heritage organization then I get the same "Oeps er ging iets mis" error message when I try to create a new object in a collection.

**Comment by lem-onade** [comment]
Hey @pietervaneverdingen 

Indeed, creating new objects was broken since https://github.com/netwerk-digitaal-erfgoed/solid-crs/pull/438 and the issue has been resolved in this pull request. It should get released and be available before tomorrow!

Sorry for any inconvenience

**Comment by pietervaneverdingen** [comment]
Thanks @lem-onade, then I will check it tomorrow again.

**Comment by pietervaneverdingen** [comment]
@lem-onade, no success so far, you can create a collection, you can create an object, but you can't find terms from the network of terms sources and you can't save the object and it also gave a root.alerts,error message ones (so, multiple issues).

**Comment by lem-onade** [comment]
Hey @pietervaneverdingen. The network of terms fix is currently in the develop branch (I assume this bug is also causing the saving issue, as some required fields are empty)

Again, I'm sorry for any inconvenience. I'll make sure this is resolved in the live version ASAP.

**Comment by lem-onade** [comment]
@pietervaneverdingen should be fixed!

**Comment by pietervaneverdingen** [comment]
@lem-onade, thanks, much better, nice new feature is that you can view the full image now. The only thing that doesn't work in the example image that I have added to a collection is that I cannot add an own term (e.g. the name of a photographer that is not available in one of the network of terms sources). And I think it is more intuitive to have a save button always visible in the top bar (and that you get a message when you try to save without entries for mandatory fields).

**Comment by lem-onade** [comment]
@pietervaneverdingen 

Thanks for the feedback! 

> The only thing that doesn't work in the example image that I have added to a collection is that I cannot add an own term (e.g. the name of a photographer that is not available in one of the network of terms sources). 

This seems to work when I try, I used the following steps:

- Click "Voeg een eigen term toe"
- A new card appears
- Click "Klik om een waarde in te vullen"
- Enter your desired value
- When ready, click the plus icon on the left or press enter
- Click "Bevestigen" as usual
- Term should be added to the field, saving should save the term to the object

We'll add this to the user manual.

**Comment by pietervaneverdingen** [comment]
@lem-onade, yes, it works (forgot to click the +-sign at the right moment).

**Pull request merged**
