### PR TITLE
feat: show sources of licenses

### PR DESCRIPTION
**Pull request by arnevandoorslaer**

### CODE REVIEW

**Comment by arnevandoorslaer** [comment]
image
image

**Comment by lem-onade** [comment]
@sdevalk See screenshots above, is this what you had in mind?

**Comment by sdevalk** [comment]
@lem-onade Perfect!

Detail: would it be possible to use a regular character casing, to make the labels less screamy? E.g. `RightsStatements.org: Auteursrechtelijk beschermd`?

**Comment by lem-onade** [comment]
> @lem-onade Perfect!
> 
> Detail: would it be possible to use a regular character casing, to make the labels less screamy? E.g. `RightsStatements.org: Auteursrechtelijk beschermd`?

Sure, but since we're taking a part of that license's URI as prefix, capitalizing the S in RightStatements.org might be a hassle. Is `Rightsstatements.org: Auteursrechtelijk beschermd` fine as well?

**Comment by sdevalk** [comment]
> > @lem-onade Perfect!
> > Detail: would it be possible to use a regular character casing, to make the labels less screamy? E.g. `RightsStatements.org: Auteursrechtelijk beschermd`?
> 
> Sure, but since we're taking a part of that license's URI as prefix, capitalizing the S in RightStatements.org might be a hassle. Is `Rightsstatements.org: Auteursrechtelijk beschermd` fine as well?

Excellent!

**Review by lem-onade — APPROVED** [review]

**Pull request merged**
