### PR TITLE
feat: added button to open presentation view from manage view

### PR DESCRIPTION
**Pull request by BelgianNoise**

### CODE REVIEW

**Comment by BelgianNoise** [comment]
I added a "sharing-like" button on the top of the page which opens the presentation view in a new tab:
image

**Comment by lem-onade** [comment]
> I added a "sharing-like" button on the top of the page which opens the presentation view in a new tab: image

@ddeboer See above comment: is this what you guys had in mind for this issue?

**Comment by lem-onade** [comment]
Does not seem to work with pods other than those on `localhost:3000`, but might be related to https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/490

vite returns 404, does not even reach the app

**Comment by BelgianNoise** [comment]
NOTE:

The requested url seems okay:
```
http://localhost:3005/
https%3A%2F%2Fpod.inrupt.com%2Farthur%2Fprofile%2Fcard%23me/
collection/
https%3A%2F%2Fpod.inrupt.com%2Farthur%2Fheritage-collections%2Fcatalog%23collection-1e3fce05-3d41-43d5-ae6f-acabd18d497c
```

But the url in the address bar is:
```
http://localhost:3002/
undefinedhttps%3A%2F%2Fpod.inrupt.com%2Farthur%2Fprofile%2Fcard%23me/
collection/
https%3A%2F%2Fpod.inrupt.com%2Farthur%2Fheritage-collections%2Fcatalog%23collection-1e3fce05-3d41-43d5-ae6f-acabd18d497c
```

**Comment by ddeboer** [comment]
> @ddeboer See above comment: is this what you guys had in mind for this issue? Also: should this button exist for the collection objects as well?

Yes, looks good! The button makes sense for individual objects as well as long as that deep-links to the object in the presentation app.

**Comment by lem-onade** [comment]
I've looked into this and it's probably something to to with `vite serve`

Running with `npm run start` after building seems to work 'fine'. Not great because https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/490 still crashes the page, but I think the 404s are only local and nothing to worry about.

Probably related, although the app can be reached when the dot is not part of the last fragment: https://github.com/vitejs/vite/issues/5632

**Review by lem-onade — CHANGES_REQUESTED** [review]
As discussed above, the same icon/link can be added on the object page.

**Pull request merged**
